### ISSUE TITLE
Gems moving away after certain move

### ISSUE THREAD

**Issue by tkolenbrander** [tkolenbrander/Bejeweld-Group33#15]
**Actions performed**
1. A random gem is selected.
2. An adjacent gem is clicked. Make sure switching the random and adjacent gem does NOT make a move.

**Expected result**
First the two gems switch position.
Then they move back to their original position.

**Actual result**
The gems move away from each other. When you select a random gem and a gem east from it, the first selected gem will move west and the second selected gem will move east.

**Possible cause**
The first animation of the gems switching position is not performed, only the second animation in which the gems should move back to their original position. However, their current position hasn't changed so the gems move away from each other.

**Comment by breijm** [comment]
TimelineController.java - 142,143,147,148 
The KeyValue endValue is 0 on all these lines, meaning you want the image view to return to where it was. This solves bug 15.

An image view starts at a 0 position, after a swap it has been moved by 65 units in a particular direction. Debug the ivXXX.xProperty or the ivXXX.yProperty in the swap method to see the values change.

Bug 16 is related to this, the new tiles end location is incorrectly calculated and thus appears out of place. I suspect that the gaps exist because only the visual part is incorrect, the internal data correctly stores that there is a gem at that location. Once again debug the position properties.

Hope this helps!

**Comment by tkolenbrander** [comment]
Changing the keyvalues in TimelineController.swap fxied it.
